include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #
    public_member_api_docs: false
    no_default_cases: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    one_member_abstracts: false
    use_setters_to_change_properties: false
    avoid_dynamic_calls: false
analyzer:
  errors:
    invalid_annotation_target: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_collection_literal: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/messages_*.dart"
    - "**/strings.dart"
